# Module manifest for module 'sdwheeler.ArgumentCompleters'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 12/12/2025

@{
    RootModule        = './sdwheeler.ArgumentCompleters.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '90fcbe5c-8085-434a-8396-41459f88429a'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description       = 'My essential tools to load in my profile.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    TypesToProcess = @()
    FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-MyArgumentCompleter'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData       = @{
        PSData = @{
            Tags                     = @()
            LicenseUri               = 'https://github.com/sdwheeler/tools-by-sean/blob/main/LICENSE'
            ProjectUri               = 'https://github.com/sdwheeler/tools-by-sean/tree/main/modules/sdwheeler.ArgumentCompleters'
            RequireLicenseAcceptance = $false
        }
    }
}