# Module manifest for module 'sdwheeler.ROBTools'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.ROBTools.psm1'
    ModuleVersion     = '1.1.0'
    GUID              = 'bc4d45eb-8c76-4903-91db-2c65a360cfee'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description       = 'Collection of tools use to create monthly ROB reports.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    RequiredAssemblies = @(".\Microsoft.Azure.Kusto.Tools\netcoreapp2.1\Kusto.Data.dll")
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-AllIssues',
        'Get-AllPRs',
        'Invoke-KustoForGitHubId'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData       = @{
        PSData = @{
            Tags                     = @()
            LicenseUri               = 'https://github.com/sdwheeler/tools-by-sean/blob/main/LICENSE'
            ProjectUri               = 'https://github.com/sdwheeler/tools-by-sean/tree/main/modules/sdwheeler.ROBTools'
            RequireLicenseAcceptance = $false
        }
    }
}
