# Module manifest for module 'sdwheeler.FileManagement'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.FileManagement.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = 'b6b0a4e7-f502-4c3d-aeae-2f54f0e4c08d'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description = 'Collection of command for working with files and the filesystem.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'New-Directory',
        'Get-FileEncoding',
        'Get-JpegMetadata',
        'Get-MediaInfo',
        'Set-MedaInfo'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData = @{
        PSData = @{
            Tags = @()
            LicenseUri = 'https://github.com/sdwheeler/tools-by-sean/blob/main/LICENSE'
            ProjectUri = 'https://github.com/sdwheeler/tools-by-sean/modules/sdwheeler.FileManagement'
            RequireLicenseAcceptance = $false
        }
    }
}
