# Module manifest for module 'sdwheeler.FileManagement'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.FileManagement.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = 'b6b0a4e7-f502-4c3d-aeae-2f54f0e4c08d'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    # Description = ''
    # PowerShellVersion = ''
    # RequiredModules = @()
    RequiredAssemblies = @("$env:USERPROFILE\Documents\PowerShell\modules\TagLib\Libraries\TagLibSharp.dll")
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-RelativePath',
        'New-Directory',
        'Get-FileEncoding',
        'Get-IniContent',
        'Out-IniFile',
        'Fix-RarNames',
        'Get-JpegMetadata',
        'Get-MediaInfo',
        'Set-MedaInfo'
    )
    CmdletsToExport   = '*'
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
            # Prerelease = ''
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable
}
