# Module manifest for module 'sdwheeler.SystemUtils'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.SystemUtils.psm1'
    ModuleVersion     = '1.0.4'
    GUID              = '28710aa7-3458-4ffe-934c-32759454bbc2'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description       = 'A collection of Windows system utilities.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    FormatsToProcess  = @('MUHistory.Format.ps1xml', 'RdpError.Format.ps1xml')
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-AssetInfo',
        'Get-ErrorCode',
        'Get-IpsumLorem',
        'Get-LogonEvents',
        'Get-MUHistory',
        'Get-RdpCode',
        'Get-RestartEvents',
        'Get-TcpStatus',
        'Get-User32Reason',
        'Get-WeekNumber'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData       = @{
        PSData = @{
            Tags                     = @()
            LicenseUri               = 'https://github.com/sdwheeler/tools-by-sean/blob/main/LICENSE'
            ProjectUri               = 'https://github.com/sdwheeler/tools-by-sean/modules/sdwheeler.SystemUtils'
            RequireLicenseAcceptance = $false
        }
    }
}
