# Module manifest for module 'sdwheeler.SystemUtils'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.SystemUtils.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '28710aa7-3458-4ffe-934c-32759454bbc2'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description = 'A collection of Windows system utilities.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-AsciiTable',
        'Get-ErrorCode',
        'Get-KBArticle',
        'Get-LogonEvents',
        'Get-RestartEvents',
        'Get-TcpStatus',
        'Get-User32Reason',
        'List-MUHistory'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData = @{
        PSData = @{
            Tags = @()
            LicenseUri = 'https://github.com/sdwheeler/tools-by-sean/blob/main/LICENSE'
            ProjectUri = 'https://github.com/sdwheeler/tools-by-sean/modules/sdwheeler.SystemUtils'
            RequireLicenseAcceptance = $false
        }
    }
}
