# yaml-language-server: $schema=https://gh-dash.dev/schema.json
include:
  - common.yml

issuesSections:
  - title: Distros
    filters: is:open repo:PowerShell/PowerShell label:Distribution-Request,Distribution-Supported,Distribution-Declined
  - title: DSRs
    filters: is:open repo:PowerShell/PowerShell "[DSR]"
  - title: DotDocker
    filters: is:open repo:dotnet/dotnet-docker

prSections:
  - title: Distros
    filters: is:open repo:PowerShell/PowerShell label:Distribution-Request,Distribution-Supported,Distribution-Declined
  - title: DSRs
    filters: is:open repo:PowerShell/PowerShell "[DSR]"
  - title: PSDocker
    filters: is:open repo:PowerShell/PowerShell-Docker
  - title: DotDocker
    filters: is:open repo:dotnet/dotnet-docker
