# yaml-language-server: $schema=https://gh-dash.dev/schema.json
include:
  - common.yml

issuesSections:
  - title: PSDocs
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs
  - title: PSMods
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-Modules
  - title: PSGet
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-PSGet
  - title: CSCode
    filters: is:open repo:Azure/CloudShell label:Area-documentation
  - title: WinPS
    filters: is:open repo:MicrosoftDocs/windows-powershell-docs
  - title: AzPS
    filters: is:open repo:MicrosoftDocs/azure-docs-powershell
    limit: 20

prSections:
  - title: PSDocs
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs
  - title: PSMods
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-Modules
  - title: PSGet
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-PSGet
  - title: PSSDK
    filters: is:open repo:MicrosoftDocs/powershell-docs-sdk-dotnet
  - title: AzureDocs
    filters: is:open repo:MicrosoftDocs/azure-docs-pr repo:MicrosoftDocs/azure-docs label:azure-cloud-shell/svc
  - title: CSCode
    filters: is:open repo:Azure/CloudShell
  - title: WinPS
    filters: is:open repo:MicrosoftDocs/windows-powershell-docs
  - title: AzPS
    filters: is:open repo:MicrosoftDocs/azure-docs-powershell
    limit: 20
