# yaml-language-server: $schema=https://gh-dash.dev/schema.json
include:
  - common.yml

issuesSections:
  - title: PSSA
    filters: is:open repo:PowerShell/PSScriptAnalyzer
  - title: PlatyPS
    filters: is:open repo:PowerShell/platyPS
  - title: PSResourceGet
    filters: is:open repo:PowerShell/PSResourceGet
  - title: PSReadLine
    filters: is:open repo:PowerShell/PSReadLine

prSections:
  - title: PSSA
    filters: is:open repo:PowerShell/PSScriptAnalyzer
  - title: PlatyPS
    filters: is:open repo:PowerShell/platyPS
  - title: PSResourceGet
    filters: is:open repo:PowerShell/PSResourceGet
  - title: PSReadLine
    filters: is:open repo:PowerShell/PSReadLine
