# yaml-language-server: $schema=https://gh-dash.dev/schema.json
include:
  - common.yml

issuesSections:
  - title: Documentarian
    filters: is:open repo:microsoft/Documentarian
  - title: ToolModules
    filters: is:open repo:sdwheeler/ToolModules
  - title: Dash
    filters: is:open repo:dlvhdr/gh-dash
  - title: GhCLI
    filters: is:open repo:cli/cli
  - title: Vale
    filters: is:open repo:errata-ai/vale
    limit: 50 # optional limit per section

prSections:
  - title: Documentarian
    filters: is:open repo:microsoft/Documentarian
  - title: ToolModules
    filters: is:open repo:sdwheeler/ToolModules
  - title: Dash
    filters: is:open repo:dlvhdr/gh-dash
  - title: GhCLI
    filters: is:open repo:cli/cli
  - title: Vale
    filters: is:open repo:errata-ai/vale
    limit: 50 # optional limit per section
