# Module manifest for module 'sdwheeler.GitTools'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
@{
    RootModule        = 'sdwheeler.GitTools.psm1'
    ModuleVersion     = '2.2.1'
    GUID              = '7e0bfe6d-a3a7-44ff-8a04-8b471d2d4f43'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description       = 'Collection of tools to work with Git and GitHub repositories.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    FormatsToProcess = @(
        'BranchStatus.Format.ps1xml'
        'RepoLabel.Format.ps1xml'
    )
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-RepoRootList'
        'New-RepoRootList'
        'Add-RepoRoot'
        'Disable-RepoRoot'
        'Enable-RepoRoot'
        'Find-GitRepo'
        'Invoke-GitHubApi'
        'Get-RepoCacheAge'
        'Get-MyRepos'
        'Get-RepoData'
        'New-RepoData'
        'Remove-RepoData'
        'Update-RepoData'
        'Get-DefaultBranch'
        'Get-GitRemote'
        'Set-LocationRepoRoot'
        'Get-GitHubLabel'
        'Add-GitHubLabel'
        'Remove-GitHubLabel'
        'Set-GitHubLabel'
        'Import-GitHubLabel'
        'Get-RepoStatus'
        'Open-Repo'
        'Open-Branch'
        'Sync-Branch'
        'Sync-Repo'
        'Sync-AllRepos'
        'Remove-Branch'
        'Get-BranchInfo'
        'Get-GitMergeBase'
        'Get-BranchDiff'
        'Get-LastCommit'
        'Get-PrFiles'
        'Get-PrMerger'
        'New-MergeToLive'
        'New-PrFromBranch'
        'Get-Issue'
        'Close-Issue'
        'New-Issue'
        'Add-IssueComment'
        'Add-IssueLabel'
        'Get-IssueLabel'
        'Remove-IssueLabel'
        'Set-IssueLabel'
        'Get-DevOpsGitHubConnections'
        'Get-DevOpsWorkItem'
        'New-DevOpsWorkItem'
        'Update-DevOpsWorkItem'
        'Import-GHIssueToDevOps'
        'New-IssueBranch'
    )
    CmdletsToExport   = @()
    VariablesToExport = ''
    AliasesToExport   = 'cdr', 'goto', 'checkout', 'syncall', 'nib', 'rmbr'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData       = @{
        PSData = @{
            Tags                     = @()
            LicenseUri               = 'https://github.com/sdwheeler/tree/main/tools-by-sean/blob/main/LICENSE'
            ProjectUri               = 'https://github.com/sdwheeler/tree/main/tools-by-sean/modules/sdwheeler.GitTools'
            RequireLicenseAcceptance = $false
        }
    }
}
