# Module manifest for module 'sdwheeler.GitTools'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.GitTools.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '7e0bfe6d-a3a7-44ff-8a04-8b471d2d4f43'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    # Description = ''
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-MyRepos',
        'Show-Repo',
        'Goto-Repo',
        'Checkout-Branch',
        'Sync-Branch',
        'Sync-Repo',
        'Sync-AllRepos',
        'Kill-Branch',
        'Get-GitMergeBase',
        'Get-GitBranchChanges',
        'Get-BranchStatus',
        'Get-RepoStatus',
        'Invoke-GitHubApi',
        'List-Labels',
        'Get-PrFiles',
        'List-PrMerger',
        'Get-Issue',
        'Get-IssueList',
        'New-PrFromBranch',
        'New-DevOpsWorkItem',
        'Import-GitHubIssueToTFS',
        'New-MergeToLive',
        'New-IssueBranch'
    )
    CmdletsToExport   = '*'
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
            # Prerelease = ''
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable
}
