# Module manifest for module 'sdwheeler.ADUtils'
# Generated by: Sean D. Wheeler <sewhee@microsoft.com>
# Generated on: 9/10/2021
@{
    RootModule        = '.\sdwheeler.ADUtils.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '9f48c392-0ac8-4e08-bbad-055491ab0d0f'
    Author            = 'Sean D. Wheeler <sewhee@microsoft.com>'
    CompanyName       = 'Microsoft'
    Copyright         = '(c) Microsoft. All rights reserved.'
    Description = 'Collection of commands to work with Active Directory.'
    # PowerShellVersion = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @(
        'Get-XADUserPasswordExpirationDate',
        'Get-ADUserPhone',
        'Get-LocalGroupMembership',
        'Get-ADUserPhoto',
        'Set-ADUserPhoto'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = '*'
    # List of all files packaged with this module
    # FileList = @()
    # HelpInfoURI = ''
    PrivateData = @{
        PSData = @{
            Tags = @()
            LicenseUri = 'https://github.com/sdwheeler/tools-by-sean/blob/main/LICENSE'
            ProjectUri = 'https://github.com/sdwheeler/tools-by-sean/tree/main/modules/sdwheeler.ADUtils'
            RequireLicenseAcceptance = $false
        }
    }
}
